<?php
$lang['home_maintext']      = "Naslednja generacija elementary OS je tukaj. Lahek in lep. Čisto nove aplikacije. Izpopolnjen videz. Povej ceno ali prenesi brezplačno.";
$lang['home_download']      = "Prenesi";
$lang['home_payment']       = "Plačilo";
$lang['home_amount']        = "Količina";  // Amount of money
$lang['home_method']        = "Metoda";  // Method of payment
$lang['home_processor']     = "Procesor";
$lang['home_creditcard']    = "Kreditna kartica";
$lang['home_direct']        = "Neposredno"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Prenesi Luno brezplačno";
$lang['home_elementary_is'] = "elementary je:";
$lang['home_point1']        = "Za skupnost.";
$lang['home_expl1']         = "elementary ima en cilj: zagotoviti najboljšo možno izkušnjo za našo skupnost. Žene nas želja, da bi bili boljši, ne denar. Prostovoljcev ne zanima profit, ženejo jih cilji.";
$lang['home_point2']        = "Transparenten in odprt.";
$lang['home_expl2']         = "Verjamemo v moč odprte kode in svetovnega medsebojnega sodelovanja. To pomeni, da lahko vsak prenese, uporabi, spremeni in prispeva h kodi, ki smo jo napisali, z razlogom, da njihove zamisli oživijo. Koda je razvita na odprtem. To pomeni, da je desettisočim razvijalcem po celem svetu na voljo za pregled, nadzor in izboljšanje.  All before it hits your system. Vse, preden pride na vaš sistem.";
$lang['home_point3']        = "Lep in uporaben.";
$lang['home_expl3']         = "elementary gradijo oblikovalci in razvijalci, ki verjamejo, da so lahko računalniki lahki za uporabo, zabavni in čudovito lepi. S postavitvijo dizajna na prvo mesto, zagotovimo, da ne bomo ogrozili kakovosti in uporabnosti.";
$lang['home_point4']        = "Sodobno računalništvo.";
$lang['home_expl4']         = "elementary OS je brezplačna alternativa za Windows na PC-ju in OS X na Mac računalnikih. Kot pričakovano, ima hiter spletni brskalnik in trgovino s tisočimi aplikacijami. In še nekaj stvari, ki jih morda ne pričakuješ, kot so brezplačne posodobitve in nič znanih virusov.";
$lang['home_point5']        = "Hiter.";
$lang['home_expl5']         = "Luna je bila zasnovana za hitrost. Zažene se hitro, prijavi se v trenutku in uporablja le najnujnejše vire za svoje delovanje. Aplikacije tečejo noro hitro. Luna teče na istem Linux jedru, tako kot najhitrejši superračunalnik na svetu.";
$lang['home_point6']        = "Poln funkcionalnosti";
$lang['home_expl6']         = "Ko namestiš elementary, ne nameščaš samo operacijskega sistema. Nameščaš odlično zbirko aplikacij narejenih po meri, ki ti omogočajo, da se takoj spraviš k delu. Enostavno lahko deskaš po spletu, pregleduješ svojo elektronsko pošto, poslušaš glasbo in opravljaš vsakodnevna opravila ali užitke.";
$lang['home_app1']          = "Brskaj po albumih, izdelaj glasbene imenike, ocenjuj pesmi in oglej podobne komade.";
$lang['home_app2']          = "Deskaj po spletu z isto hitrostjo kot na Google Chrome in Apple Safari.";
$lang['home_app3']          = "Poveži se z Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! in drugimi.";
$lang['home_app4']          = "Pregleduj več uporabniških računov hkrati. Bodi obveščen kar na namizju. Prebiraj svojo pošto in pogovore.";
$lang['home_app5']          = "Uvozi, organiziraj in uredi slike. Izdelaj predstavitev. Deli kar želiš na Facebook in Flickr.";
$lang['home_app6']          = "Vedno ostati na samem vrhu novosti. Takojšnje posodobitve, brezplačne za vedno.";
$lang['home_point7']        = "V celoti dostopen";
$lang['home_expl7']         = "elementary gradijo različne vrste ljudi iz vsega sveta, zato ne preseneča, da je Luna zgrajena s tem v mislih. Sistem je založen z aplikacijami in prilagoditvami za osebe z motorično okvaro ter okvaro sluha in vida.";
$lang['home_point8']        = "Varen";
$lang['home_expl8']         = "Luna zgrajena na trdnem temelju jedra Linux (isto programje, ki ga uporablja ameriško Ministrstvo za obrambo, kitajska banka in drugi). Luna nima znanih virusov, kar pomeni, da ne potrebuješ nobenega antivirusa, ki bi drugače upočasnil sistem. Luna dobi varnostne posodobitve takoj, ko je nek problem odkrit. To pomeni, da ne rabite čakati na najbolj varen sistem.";
$lang['home_point9']        = "Brezplačen in prost";
$lang['home_expl9']         = "elementary OS je brezplačen in odprtokoden sistem. Nobenih dragih računov, nejasnih pogodb, poskusnih dob ali restriktivne zaščite pred kopiranjem sistema. Luna lahko namestiš na ne omejeno število naprav, kot tudi na naprave svojih prijatelje.";
$lang['home_point10']       = "Pripravljen za aplikacije";
$lang['home_expl10']        = "elementary OS ima vgrajeno trgovino z nešteto brezplačnimi aplikacijami. Hitro lahko najdeš vse kar potrebuješ, brez strahu pred virusi z interneta.";
$lang['home_whatis']        = "Kaj je"; // Whole sentence reads "what is elementary OS?"
