<?php
$lang['home_maintext']  	= "Die nächste Generation von elementary OS ist da. Schnell, flexibel und wunderschön. Völlig neue Apps. Ein verbessertes Aussehen. Bestimmen Sie den Preis oder laden Sie es kostenlos herunter.";
$lang['home_download']  	= "Herunterladen";
$lang['home_payment']   	= "Bezahlen";
$lang['home_amount']    	= "Betrag";  // Amount of money
$lang['home_method']    	= "Bezahlmethode";  // Method of payment
$lang['home_processor'] 	= "Prozessor";
$lang['home_creditcard']	= "Kreditkarte";
$lang['home_direct']    	= "HTTP Download"; // Direct download (via HTTP)
$lang['home_luna_free'] 	= "Laden Sie Luna kostenlos herunter";
$lang['home_elementary_is'] = "elementary ist:";
$lang['home_point1']    	= "Von und für die Community.";
$lang['home_expl1']     	= "elementary hat ein Ziel: Wir wollen unserer Community das bestmögliche Erlebnis bieten. Mit dem Fokus auf Qualität und nicht auf Profit.";
$lang['home_point2']    	= "Transparent und Offen.";
$lang['home_expl2']     	= "Wir glauben an die Kraft von Open-Source und globale Zusammenarbeit. Das heißt jeder kann elementary OS kostenlos herunterladen, benutzen, verändern und dazu beitragen, den Code und seine Idee zu verwirklichen. Der Quellcode wird öffentlich entwickelt, das heißt er kann gesichtet, getestet und verbessert werden - durch zehntausende Entwickler weltweit. All das, bevor dieser Code überhaupt auf Ihrem System landet.";
$lang['home_point3']    	= "Ansprechend und Benutzerfreundlich.";
$lang['home_expl3']     	= "elementary wird von Designern und Entwicklern erstellt, welche überzeugt sind, dass Computer einfach und wunderschön sein können. Dadurch, dass Design bei uns an erster Stelle steht, stellen wir sicher, dass es keine Kompromisse bezüglich Qualität oder Benutzerfreundlichkeit gibt.";
$lang['home_point4']    	= "Ein Modernes System.";
$lang['home_expl4']     	= "elementary OS ist eine freie Alternative für Windows und Mac OS X. Es kommt mit allem was Sie erwarten, wie einem schnellen Web-Browser und einem App-Store mit tausenden Anwendungen. Plus einigen Extras, die Sie vielleicht nicht erwarten, wie kostenlose Aktualisierungen und keine bekannten Viren.";
$lang['home_point5']    	= "Schnell";
$lang['home_expl5']     	= "Luna wurde von Grund auf mit dem Ziel entwickelt ressourcenschonend zu sein. Es startet schnell, das Anmelden ist instantan, und nutzt nur das Nötigste an Ressourcen, damit Sie sich auch über einen Geschwindigkeitsschub für Ihre Anwendungen freuen können. Mit Luna erhalten Sie außerdem dasselbe Linux-Fundament, welches auch die schnellsten Supercomputer der Welt antreibt.";
$lang['home_point6']    	= "Voller Funktionen";
$lang['home_expl6']     	= "Wenn Sie elementary installieren, bekommen Sie nicht nur irgendein Betriebssystem. Sie erhalten eine ausgezeichnete Sammlung von maßgeschneiderten Anwendungen, damit Sie direkt loslegen können. Surfen Sie bequem im Web, prüfen Sie Ihre E-Mails, hören Sie Musik und bewältigen Sie tägliche Aufgaben oder Freuden.";
$lang['home_app1']      	= "Stöbern Sie durch Alben, Legen Sie Wiedergabelisten an, Bewerten Sie Musiktitel und lassen Sie sich ähnlicher Musiktitel anzeigen.";
$lang['home_app2']      	= "Surfen Sie im Web mit der Geschwindigkeit der selben Rendering Engine die in Google Chrome und Apple Safari Verwendung findet.";
$lang['home_app3']      	= "Verbinden Sie sich mit Jabber, Facebook, Google Hangouts, AIM, IRC, Yahoo! und vielen weiteren Diensten.";
$lang['home_app4']      	= "Verwalten von mehreren Konten, Desktop-Benachrichtigungen, und lesen von Mails in Form von Konversationen.";
$lang['home_app5']      	= "Importieren, Organisieren, und Bearbeiten von Fotos. Zusammenstellen von Slideshows. Teilen via Facebook oder Flickr.";
$lang['home_app6']      	= "Immer auf dem aktuellen Stand der Technik. Kostenlose, zeitlich unbefristete Aktualisierungen.";
$lang['home_point7']    	= "Barrierefrei";
$lang['home_expl7']     	= "Verschiedenste Menschen aus aller Welt nutzen elementary, also ist es kein Wunder dass Luna darauf hin ausgelegt wurde. Es kommt mit Apps und Anpassungen für Menschen mit eingeschränktem Hör-, oder Sehvermögen, und Unterstützung für Menschen mit eingeschränkter Motorik.";
$lang['home_point8']    	= "Zuverlässig und Sicher";
$lang['home_expl8']     	= "Luna hat mit Linux eine solide Basis zur Grundlage (dieselbe Software die beim US Department of Defense, der Bank von China, und vielen weiteren Verwendung findet). Es gibt keine bekannten Viren, was bedeutet das lästige Anti-Viren Software überflüssig ist. Luna erhält Sicherheitsupdates schnellstmöglich nachdem Lücken erkannt wurden.";
$lang['home_point9']    	= "100% kostenlos";
$lang['home_expl9']     	= "elementary OS ist komplett kostenlos, in Sachen Preis und Lizensierung. Es gibt keine Kosten, verwirrende Nutzerbestimmungen, zeitliche Einschränkungen, oder einen bevormundenden Kopierschutz. Sie können Luna auf so vielen Rechnern wie Sie möchten installieren oder an Ihre Freunde weitergeben.";
$lang['home_point10']   	= "Bereit für Apps";
$lang['home_expl10']    	= "elementary OS kommt mit einem eingebauten App Store, gefüllt mit tausenden kostenlosen Anwendungen. Finden Sie schnell wonach Sie suchen ohne sich um Malware aus dem Web Sorgen zu machen.";
$lang['home_whatis']        = "Was ist" ; // Whole sentence reads "what is elementary OS?"

