<?php
$lang['home_maintext']      = "Następna generacja systemu elementary już jest. Lekki i piękny. Wiele nowych aplikacji. Poprawiony wygląd. Podaj swoją cenę lub pobierz za darmo.";
$lang['home_download']      = "Pobierz";
$lang['home_payment']       = "Płatność";
$lang['home_amount']        = "Kwota";  // Amount of money
$lang['home_method']        = "Metoda";  // Method of payment
$lang['home_processor']     = "Procesor";
$lang['home_creditcard']    = "Karta kredytowa";
$lang['home_direct']        = "Bezpośrednio"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Pobierz Lunę za darmo";
$lang['home_elementary_is'] = "elementary jest:";
$lang['home_point1']        = "Napędzany przez społeczność.";
$lang['home_expl1']         = "elementary posiada jeden cel: podarowanie swojej społeczności najlepszych możliwych doświadczeń. Pracujemy, bo chcemy się rozwijać, a nie zarabiać. Nasi współpracowanicy nie są nastawieni na zarobek, a właśnie na realizację celu.";
$lang['home_point2']        = "Transparentny i otwarty.";
$lang['home_expl2']         = "Wierzymy w potęgę otwartego oprogramowania i międzynarodowej współpracy. To oznacza, że każdy może pobierać, używać, modyfikować i przyczyniać się do wdrażania pomysłów w życie. Tworzony kod jest otwarty, możliwy do podglądu, badania, i poprawiany przez wielu doświadczonych ludzi z całego świata. Wszystko, zanim trafi do systemu.";
$lang['home_point3']        = "Piękny i użyteczny.";
$lang['home_expl3']         = "elementary jest tworzony przez grafików i programistów, któzy wierzą, że komputery powinny być proste w użyciu, dawać frajdę i wyglądać. Stawiamy wygląd na pierwszym miejscu dzięki czemu nie musiamy iść na kompromis między wyglądem, a użytecznością.";
$lang['home_point4']        = "Nowoczesny.";
$lang['home_expl4']         = "elementary OS jest darmową alternatywą dla Windows na PC lub OS X na Makach. Posiada to, czego oczekujesz, czyli szybką przeglądarkę i centrum aplikacji zawierające setki tysięcy pozycji. Do tego rzeczy, których nie oczekujesz, takie jak całkowicie darmowe aktualizacje i brak wirusów.";
$lang['home_point5']        = "Szybki";
$lang['home_expl5']         = "Luna została zaprojektowana od podstaw. Uruchamia się szybko, loguje błyskawiczniei używa minimum zasobów komputera, dzięki czemu aplikacje działają szybko i sprawnie. Z Luną dostajesz tego samego Linuksa, który napędza najpotężniejsze superkomputery świata.";
$lang['home_point6']        = "Pełen funkcji";
$lang['home_expl6']         = "Gdy instalujesz elementary nie umieszczasz na dysku jedynie systemu operacyjnego. Instalujesz świetne aplikacje, które pomogą Ci w codziennej pracy przy komputerze. Łatwo przeglądaj sieć, sprawdzaj swoją skrzynkę email, słuchaj muzyki i wykonuj codzienne czynności z przyjemnością.";
$lang['home_app1']          = "Przeglądaj albumy, twórz playlisty, oceniaj piosenki i słuchaj podobnych utworów.";
$lang['home_app2']          = "Przeglądaj sieć z tą samą prędkością i łatwością, jak przy użyciu Google Chrome czy Apple Safari.";
$lang['home_app3']          = "Połącz się z sieciami Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! i wieloma innymi.";
$lang['home_app4']          = "Korzystaj z kilku kont, otrzymuj powiadomienia o nowej poczcie i czytaj maile jako konwersacje.";
$lang['home_app5']          = "Importuj, organizuj, edytuj zdjęcia. Twórz pokazy slajdów. Udostępniaj na Facebooku lub Flickrze.";
$lang['home_app6']          = "Pozostań na czasie. Otrzymuj aktualizacje poprawnie, na zawsze, za darmo.";
$lang['home_point7']        = "W pełni dostępny";
$lang['home_expl7']         = "Przeróżni ludzie z całego świata pomagają tworzyć elementary, dlatego nie powinno być dla nikogo zaskoczeniem, że Luna jest tworzona dla różnych ludzi. Jest dostarczona z mechanizmami pomagającymi osobom z problemami wzroku, słuchu, a także z problemami ruchowymi.";
$lang['home_point8']        = "Bezpieczny";
$lang['home_expl8']         = "Luna jest zbudowana na bazie jądra Linux (tego samego, który zasila departament obrony USA, Bank Chin i inne). Nie ma znanych wirusów, dlatego nie potrzebujesz antywirusa zajmującego zasoby komputera. Luna otrzymuje aktualizacje bezpieczeństwa od razu, gdy zostanie wykryty problem - nie trzeba czekać, jak w przypadku najpopularniejszych systemów.";
$lang['home_point9']        = "W 100% darmowy";
$lang['home_expl9']         = "elementary OS jest zupełnie darmowy, zarówno w zakresie cen i licencji. Brak tu kosztownych opłat, niezrozumiałych umów, okresów próbnych, czy restrykcyjnych zabezpieczń przed kopiowaniem. Lunę możesz zainstalować na tak wielu komputerach, ilu zdołasz i kopiować tyle razy, ile uznasz za właściwe.";
$lang['home_point10']       = "Gotów na aplikacje";
$lang['home_expl10']        = "elementary OS zawiera wbudowane centrum aplikacji, zawierające tysiące darmowych aplikacji. Szybko znajdź to, co Cię interesuje omijając sieciowe śmieci i niepotrzebne dodatki.";
$lang['home_whatis']        = "Czym jest"; // Whole sentence reads "what is elementary OS?"

