<?php
$lang['home_maintext']      = "Le dernier elementary OS est arrivé. Léger et somptueux. De toutes nouvelles applications. Une apparence raffinée. Au prix que vous souhaitez, ou gratuitement.";
$lang['home_download']      = "Télécharger";
$lang['home_payment']       = "Paiement";
$lang['home_amount']        = "Quantité";  // Amount of money
$lang['home_method']        = "Moyen de paiement";  // Method of payment
$lang['home_processor']     = "Processeur";
$lang['home_creditcard']    = "Carte de crédit";
$lang['home_direct']        = "Direct"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Télécharger Luna gratuitement";
$lang['home_elementary_is'] = "elementary est:";
$lang['home_point1']        = "Porté par la Communauté.";
$lang['home_expl1']         = "elementary n'a qu'un seul but: fournir la meilleure expérience possible à notre communauté. C'est le désir d'être meilleur qui nous motive, pas l'argent. Les contributeurs ne maximisent pas leur profit, ils maximisent leurs résultats.";
$lang['home_point2']        = "Transparent et Ouvert.";
$lang['home_expl2']         = "Nous croyons au pouvoir du libre et de la collaboration globale. Cela signifie que n'importe qui peut télécharger, utiliser, modifier, et contribuer au code que nous avons écrit pour donner vie à ses idées. Le code est disponible publiquement, ce qui signifie qu'il est ouvert à un examen détaillé et à des améliorations par des dizaines de milliers de développeurs tout autour du monde. Tout cela avant d'être inclus dans votre système.";
$lang['home_point3']        = "Beau et Utile.";
$lang['home_expl3']         = "elementary est conçu par des désigneurs et développeurs qui pensent que les ordinateurs peuvent être intuitifs, funs, et somptueux. En favorisant le design, nous nous assurons de ne pas perdre en qualité et en convivialité.";
$lang['home_point4']        = "L'informatique Moderne.";
$lang['home_expl4']         = "elementary OS  est une alternative gratuite à Windows sur PC et à OS X sur Mac. Il contient tout ce que vous pouvez attendre de lui, comme un navigateur rapide et une bibliothèque logicielle avec des milliers d'applications. Et d'autres choses que vous n'attendiez peut-être pas, commes des mises à jour gratuites et aucun virus connu.";
$lang['home_point5']        = "Rapide";
$lang['home_expl5']         = "Luna a été imaginé pour ne pas être trop gourmand. Il démarre rapidement, vous connecte instantanément et utilise le minimum de ressources pour que vos applications profitent également d'un boost de rapidité. Et avec Luna, vous partez sur la base choisie pour les supercalculateurs les plus rapides au monde.";
$lang['home_point6']        = "Plein de Fonctionnalités";
$lang['home_expl6']         = "Lorsque vous installez elementary, vous n'installez pas qu'un système d'exploitation. Vous installez une excellente suite d'applications taillées sur mesure qui vous laissent vous concentrer sur votre travail. Surfez sur le web, consultez vos mails, écoutez de la musique, et effectuez toutes les tâches et plaisirs quotidiens .";
$lang['home_app1']          = "Naviguez par album, créez des playlists, notez les chansons et consultez des pistes similaires.";
$lang['home_app2']          = "Surfez sur le web à la vitesse des moteurs de rendu de Google Chrome et Safari d'Apple.";
$lang['home_app3']          = "Connectez-vous sur Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! et d'autres.";
$lang['home_app4']          = "Consultez plusieurs comptes, recevez des notifications sur le bureau et afficher vos mails en conversations.";
$lang['home_app5']          = "Importez, organisez et éditez vos photos. Créez un diaporama. Partagez le tout sur Facebook ou Flickr.";
$lang['home_app6']          = "Restez à la pointe. Recevez les mises à jours de suite, pour toujours, gratuitement.";
$lang['home_point7']        = "Accessible";
$lang['home_expl7']         = "Des personnes très différentes du monde entier construisent elementary, c'est donc sans surprise que Luna soit construit dans cet esprit. Il est livré avec des applications et dispositifs pour les malvoyants et malentendants, ainsi qu'une assistance pour les personnes à mobilité réduite.";
$lang['home_point8']        = "Sécurisé";
$lang['home_expl8']         = "Luna est basé sur la fondation solide offerte par Linux (le même utilisé par le département de la Défence américaine, la Banque de Chine, et d'autres). Il ne souffre d'aucun virus connu, ce qui signifie que vous n'avez pas besoin d'installer un anti-virus qui ralentit inutilement votre système. Luna bénéficie de mises à jour de sécurité dès qu'un problème est détecté, donc il n'y a pas de délai pour avoir un système sécurisé.";
$lang['home_point9']        = "100% gratuit";
$lang['home_expl9']         = "elementary OS est complètement gratuit et libre. Il n'y a aucune taxe d'utilisation ou de condition louche, pas de période d'essai ou de protections contre la copie. Vous pouvez installer Luna sur autant d'ordinateurs que vous le souhaitez et même le copier pour le transmettre à vos amis.";
$lang['home_point10']       = "Prêt pour les Applications";
$lang['home_expl10']        = "elementary OS comprend une bibliothèque logicielle remplie de milliers d'applications gratuites. Trouvez ce que vous cherchez rapidement et sans vous soucier des malwares du web.";
$lang['home_whatis']        = "Qu'est-ce qu'"; // Whole sentence reads "what is elementary OS?"
