<?php
$lang['home_maintext']      = "A nova geração do elementary OS já chegou. Leve e bonito. Novas aplicações. Um look redefinido. Faça uma oferta ou transfira-o gratuitamente.";
$lang['home_download']      = "Transferir";
$lang['home_payment']       = "Pagamento";
$lang['home_amount']        = "Quantia";  // Amount of money
$lang['home_method']        = "Método";  // Method of payment
$lang['home_processor']     = "Processador";
$lang['home_creditcard']    = "Cartão de Crédito";
$lang['home_direct']        = "Direto"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Transfira o Luna gratuitamente";
$lang['home_elementary_is'] = "O elementary é:";
$lang['home_point1']        = "Conduzido pela Comunidade.";
$lang['home_expl1']         = "O elementary tem um único objetivo: Proporcionar a melhor experiência à nossa comunidade. Somos movidos pelo desejo de fazer melhor, não por pagamentos. Os contribuidores não são maximizadores de lucro, mas sim de um propósito.";
$lang['home_point2']        = "Transparente e Aberto.";
$lang['home_expl2']         = "Acreditamos no poder do código aberto e colaboração global. Isso significa que qualquer um pode transferir, usar, modificar e contribuir para o código que escrevemos para dar vida às ideias. O código é desenvolvido abertamente, estando disponível para revisão, pesquisa e melhoramento por milhares de programadores em todo o mundo. Tudo antes de chegar ao seu sistema.";
$lang['home_point3']        = "Apelativo e Usável.";
$lang['home_expl3']         = "O elementary é criado por designers e programadores que acreditam que os computadores podem ser fáceis de usar, divertidos e deslumbrantes. Ao colocar o design em primeiro, certificamo-nos que não estamos a comprometer a qualidade ou a usabilidade.";
$lang['home_point4']        = "Computação Moderna.";
$lang['home_expl4']         = "O elementary OS é um substituto gratuito do Windows em PCs e do OS X em Macs. Vem com tudo o que esperava de um sistema operativo, como um navegador de internet rápido e uma Loja de Aplicações com milhares de aplicações. E algumas coisas que não espera, como atualizações gratuitas e inexistência de bugs.";
$lang['home_point5']        = "Veloz";
$lang['home_expl5']         = "O Luna foi projetado desde o início para ser rápido. Inicia rapidamente, entra instantaneamente, e usa o menor número de recursos para que as suas aplicações sejam mais rápidas. E com o Luna, obtém a mesma base Linux escolhida para os supercomputadores mais rápidos.";
$lang['home_point6']        = "Cheio de Funcionalidades";
$lang['home_expl6']         = "Quando instala o elementary, não está a instalar apenas um sistema operativo. Está a instalar um excelente conjunto de aplicações feitas à medida que lhe permitem ir direito ao assunto. Navegue na internet facilmente, veja o seu email, ouça as suas músicas e enfrente as suas tarefas diárias ou prazeres.";
$lang['home_app1']          = "Navegue por álbuns, faça listas de reprodução, classifique músicas, e veja faixas semelhantes.";
$lang['home_app2']          = "Navegue na internet com a velocidade do mesmo motor do Google Chrome e Apple Safari.";
$lang['home_app3']          = "Ligue-se ao Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! e outros.";
$lang['home_app4']          = "Veja múltiplas contas, receba notificações e leia as suas conversas de email.";
$lang['home_app5']          = "Importe, Organize, e Edite fotos. Faça apresentações. Partilhe no Facebook ou Flickr.";
$lang['home_app6']          = "Mantenha-se na vanguarda. Obtenha atualizações imediatamente, para sempre, gratuitamente.";
$lang['home_point7']        = "Totalmente Acessível";
$lang['home_expl7']         = "Todos os tipos de pessoas por todo mundo fazem o elementary, assim não é surpresa que o Luna seja feito a pensar em todos. Traz incluídas aplicações e melhoramentos para os deficientes visuais e auditivos, bem como assistência para os deficientes motores.";
$lang['home_point8']        = "Seguro";
$lang['home_expl8']         = "O Luna é construído numa base sólida Linux (usada nas maiores empresas, como a PT, o Instituto Nacional de Estatística, entre outras). Não tem vírus conhecidos, o que significa que não necessita de um antivírus a diminuir a velocidade do sistema. O Luna recebe atualizações de segurança assim que os problemas são identificados, o que significa que não tem que esperar pelo sistema mais seguro.";
$lang['home_point9']        = "100% Grátis";
$lang['home_expl9']         = "O elementary OS é completamente grátis, tanto em termos de preço como licenciamento. Não há taxas, acordos de utilizador confusos, tempos de experiência, ou cópias de proteção restritivas. Pode instalar o Luna em quantos computadores quiser ou copiá-lo e enviá-lo aos seus amigos.";
$lang['home_point10']       = "Pronto para Apps";
$lang['home_expl10']        = "O elementary OS vem com uma loja de aplicações, repleta de milhares de aplicações gratuitas. Encontre rapidamente o que precisa sem se preocupar com vírus da internet.";
$lang['home_whatis']        = "O que é o"; // Whole sentence reads "what is elementary OS?"
