<?php
$lang['home_maintext']      = "La nueva generación de elementary OS ha llegado. Liviana y hermosa. Aplicaciones completamente nuevas. Aspecto refinado. Póngale un precio o descárgelo gratis.";
$lang['home_download']      = "Descargar";
$lang['home_payment']       = "Pago";
$lang['home_amount']        = "Cantidad";  // Amount of money
$lang['home_method']        = "Método";  // Method of payment
$lang['home_processor']     = "Procesador";
$lang['home_creditcard']    = "Tarjeta de Crédito";
$lang['home_direct']        = "Directo"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Descargar Luna gratis";
$lang['home_elementary_is'] = "elementary es:";
$lang['home_point1']        = "Manejado por la Comunidad.";
$lang['home_expl1']         = "elementary tiene un objetivo: proveer la mejor experiencia posible a nuestra comunidad. Nos mueve el deseo de mejorar, no el sueldo.";
$lang['home_point2']        = "Transparente y Abierto.";
$lang['home_expl2']         = "Creemos en el poder del código abierto y la colaboración global. Eso significa que cualquiera puede usar, modificar y contribuir al código que hemos escrito para dar vida a sus propias ideas. El código es desarrollado de forma abierta, permitiendo su escrutinio y mejoras por miles de desarrolladores alrededor del mundo.";
$lang['home_point3']        = "Hermoso y Funcional.";
$lang['home_expl3']         = "elementary es concebido por diseñadores y desarrolladores convencidos que las computadoras pueden ser fáciles de usar, divertidas y hermosas. Anteponemos diseño sin comprometer calidad o usabilidad.";
$lang['home_point4']        = "Computación Moderna.";
$lang['home_expl4']         = "elementary OS es un reemplazo gratuito a Windows en una PC y OS X en una Mac. Trae integrado lo que uno esperaría, como un navegador web rápido y una tienda de aplicaciones, además de otras cosas inesperadas como actualizaciones gratuitas y que no sea vulnerable a virus.";
$lang['home_point5']        = "Rápido";
$lang['home_expl5']         = "Luna fue diseñado desde el principio para ser ágil. Arranca rápido, inicia sesión instantáneamente y utiliza los mínimos recursos indispensables para que sus aplicaciones sean más rápidas. Con Linux recibe las mismas bases elegidas por las supercomputadoras mas rápidas del globo.";
$lang['home_point6']        = "Lleno de prestaciones";
$lang['home_expl6']         = "Cuando instala elementary no sólo esta instalando un sistema operativo. Está instalando un grupo de aplicaciones cuidadosamente seleccionadas que le permiten dedicarse directamente a su trabajo. Fácilmente navegue la web, verifique su email, escuche música y otras tareas cotidianas.";
$lang['home_app1']          = "Navegue por discos, Cree listas de reproducción, Califique canciones y encuentre otras similares.";
$lang['home_app2']          = "Navegue la web con la velocidad del mismo motor de renderizado de Google Chrome y Safari de Apple.";
$lang['home_app3']          = "Conéctese a Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! y más.";
$lang['home_app4']          = "Vea varias cuentas, reciba notificaciones en el escritorio y lea su mail ordenado en conversaciones.";
$lang['home_app5']          = "Importe, organice  y edite su fotos. Cree diapositivas. Comparta en Facebook o Flickr.";
$lang['home_app6']          = "Manténgase actualizado, siempre, gratuitamente.";
$lang['home_point7']        = "Totalmente Accesible";
$lang['home_expl7']         = "Diferentes tipos de personas alrededor del mundo desarrollan elementary, así que no sorprende que Luna sea creado así. Viene equipado con aplicaciones y ajustes para personas con afecciones a la visión y/o audición.";
$lang['home_point8']        = "Seguro y Confiable";
$lang['home_expl8']         = "Luna está hecho sobre las fundaciones de Linux (el mismo software que da soporte al Departamento de Defensa de EEUU, el Banco de China y más). No se conocen virus que lo afecten, lo que significa que no debe utilizar programas de anti-virus que ralenticen su sistema. Luna recibe actualizaciones de seguridad tan pronto como se descubren, dejándolo siempre con un sistema seguro.";
$lang['home_point9']        = "100% Libre";
$lang['home_expl9']         = "elementary OS es completamente libre, tanto en términos de licencia como de precio. No se cobran tasas, no hay contratos confusos ni periodos de prueba o restricciones de protección de copia. Puede instalar Luna en tantas computadoras como desee y hasta copiarlo y regalárselo a sus amigos.";
$lang['home_point10']       = "Extensible";
$lang['home_expl10']        = "elementary OS viene con una tienda de aplicaciones integrada, equipada con miles de aplicaciones libres. Rápidamente encuentre lo que esta buscando sin preocuparse por malware de la web.";
$lang['home_whatis']        = "Que es "; // Whole sentence reads "what is elementary OS?"
