<?php
$lang['home_maintext']      = "The next generation of elementary OS is here. Lightweight and beautiful. All-new apps. A refined look. Name your price or download for free.";
$lang['home_download']      = "Download";
$lang['home_payment']       = "Payment";
$lang['home_amount']        = "Amount";  // Amount of money
$lang['home_method']        = "Method";  // Method of payment
$lang['home_processor']     = "Processor";
$lang['home_creditcard']    = "Credit Card";
$lang['home_direct']        = "Direct"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Download Luna for free";
$lang['home_elementary_is'] = "elementary is:";
$lang['home_point1']        = "Community Driven.";
$lang['home_expl1']         = "elementary has a single goal: to provide the best possible experience for our community. We're driven by a desire to be better, not by a paycheck. Contributors aren't profit-maximizers, they're purpose-maximizers.";
$lang['home_point2']        = "Transparent and Open.";
$lang['home_expl2']         = "We believe in the power of open source and global collaboration. That means anyone can download, use, modify, and contribute to the code we've written to bring their ideas to life. The code is developed in the open, meaning it's available for review, scrutiny, and improvement by tens of thousands of developers all around the world. All before it hits your system.";
$lang['home_point3']        = "Beautiful and Usable.";
$lang['home_expl3']         = "elementary is crafted by designers and developers who believe that computers can be easy, fun, and gorgeous. By putting design first, we ensure we're not compromising on quality or usability.";
$lang['home_point4']        = "Modern Computing.";
$lang['home_expl4']         = "elementary OS is a free replacement for Windows on the PC and OS X on the Mac. It comes with what you'd expect, like a fast web browser and an app store with thousands of apps. Plus some things you may not expect, like free updates and no known viruses.";
$lang['home_point5']        = "Speedy";
$lang['home_expl5']         = "Luna has been engineered from the ground up to be light on its toes. It starts up quickly, logs in instantly, and uses the bare minimum of resources so that your apps enjoy a speed boost as well. And with Luna, you get the same Linux foundation chosen for the world’s fastest supercomputers.";
$lang['home_point6']        = "Full of Features";
$lang['home_expl6']         = "When you install elementary, you’re not just installing an operating system. You’re installing an excellent suite of custom tailored apps that let you get right to business. Easily surf the web, check your email, listen to music, and tackle everyday tasks or pleasures.";
$lang['home_app1']          = "Browse by albums, Make playlists, Rate songs, and see similiar tracks.";
$lang['home_app2']          = "Surf the web with the speed of the same rendering engine as Google Chrome and Apple Safari.";
$lang['home_app3']          = "Connect with Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! and more.";
$lang['home_app4']          = "View multiple accounts, get desktop notifications, and read your mail in conversations.";
$lang['home_app5']          = "Import, Organize, and Edit photos. Make a slideshow. Share with Facebook or Flickr.";
$lang['home_app6']          = "Always stay on the cutting edge. Get updates right away, forever, for free.";
$lang['home_point7']        = "Fully Accessible";
$lang['home_expl7']         = "Different kinds of people from all over the world build elementary, so it’s no surprise that Luna is built with this in mind. It comes stocked with apps and tweaks for the hearing and sight impaired, as well as assistance for the motor impaired.";
$lang['home_point8']        = "Safe and Secure";
$lang['home_expl8']         = "Luna is built on the rock-solid foundation of Linux (the same software that powers the US Department of Defense, the Bank of China, and more). It has no known viruses, which means no pesky anti-virus software to slow down your system. Luna receives security updates as soon as a problem is discovered, meaning there’s no waiting around for the most secure system.";
$lang['home_point9']        = "100% Free";
$lang['home_expl9']         = "elementary OS is completely free, both in terms of pricing and licensing. There are no costly fees, confusing user agreements, trial periods, or restrictive copy protections. You can install Luna on as many computers as you want or even copy it and give it away to your friends.";
$lang['home_point10']       = "Ready for Apps";
$lang['home_expl10']        = "elementary OS comes with a built-in app store, stocked with thousands of free apps. Quickly find what you’re looking for without worrying about malware from the web.";
$lang['home_whatis']        = "What is"; // Whole sentence reads "what is elementary OS?"
$lang['home_cc_paypal']     = "Credit card payments are available through PayPal";
